[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 100
via_ir = true
build_info = true
extra_output = ["storageLayout"]

[fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin/=openzeppelin/contracts/",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}"}